# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

variables:
  DATABASE_URL: postgres://vsts:ci@localhost/sea_test

steps:
  - script: |
      curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - &&
      sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" > /etc/apt/sources.list.d/pgdg.list' &&
      sudo apt-get update &&
      sudo apt-get install postgresql-10 &&
      sudo -u postgres psql -c "CREATE USER vsts WITH PASSWORD 'ci' SUPERUSER;"
      sudo -u postgres psql -c "CREATE DATABASE sea_test WITH OWNER 'vsts';"
    displayName: "Install and Setup PostgreSQL"
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"
  - script: |
      yarn install
      yarn build
    displayName: "yarn install and build"
  - script: |
      yarn test
    displayName: "yarn test"
